// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrBendaHelloWorld) DeepCopyInto(out *OrBendaHelloWorld) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrBendaHelloWorld.
func (in *OrBendaHelloWorld) DeepCopy() *OrBendaHelloWorld {
	if in == nil {
		return nil
	}
	out := new(OrBendaHelloWorld)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrBendaHelloWorld) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrBendaHelloWorldList) DeepCopyInto(out *OrBendaHelloWorldList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OrBendaHelloWorld, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrBendaHelloWorldList.
func (in *OrBendaHelloWorldList) DeepCopy() *OrBendaHelloWorldList {
	if in == nil {
		return nil
	}
	out := new(OrBendaHelloWorldList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrBendaHelloWorldList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrBendaHelloWorldSpec) DeepCopyInto(out *OrBendaHelloWorldSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrBendaHelloWorldSpec.
func (in *OrBendaHelloWorldSpec) DeepCopy() *OrBendaHelloWorldSpec {
	if in == nil {
		return nil
	}
	out := new(OrBendaHelloWorldSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrBendaHelloWorldStatus) DeepCopyInto(out *OrBendaHelloWorldStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrBendaHelloWorldStatus.
func (in *OrBendaHelloWorldStatus) DeepCopy() *OrBendaHelloWorldStatus {
	if in == nil {
		return nil
	}
	out := new(OrBendaHelloWorldStatus)
	in.DeepCopyInto(out)
	return out
}
